services:
  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/app
  db:
    container_name: "database-evoe"
    image: mysql
    command: --sql_mode=NO_ENGINE_SUBSTITUTION --explicit_defaults_for_timestamp
    restart: always
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    volumes:
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
